// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package partial

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func CartIcon() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.WriteWatchModeString(templ_7745c5c3_Buffer, 1)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = getCartItemCount().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func getCartItemCount() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_getCartItemCount_6bc9`,
		Function: `function __templ_getCartItemCount_6bc9(){const strCart = localStorage.getItem("shopping-cart");
let itemCount = 0

if (strCart?.length){
const cart = JSON.parse(strCart);

if(Array.isArray(cart)){
itemCount = cart.length;
}
}

document.getElementById("cart-widget").innerHTML = itemCount;
}`,
		Call:       templ.SafeScript(`__templ_getCartItemCount_6bc9`),
		CallInline: templ.SafeScriptInline(`__templ_getCartItemCount_6bc9`),
	}
}
