// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/andrei0427/lifeofmarrow/view/helpers"

type HomeEntity struct {
	CTA           string                        `json:"CTA"`
	Logo          helpers.StrapiMedia           `json:"Logo"`
	ImageCarousel helpers.StrapiMediaCollection `json:"ImageCarousel"`
}

func Index(props HomeEntity) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"fixed top-0 w-full h-screen transition-all ease-in-out duration-500\" _=\"on click add .-translate-y-full to me settle go to url /about remove .-translate-y-full from me\"><div class=\"swiper\"><div id=\"wallpaper-swiper\"><div class=\"swiper-wrapper\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, slide := range props.ImageCarousel.Data {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"swiper-slide\"><div class=\"aspect-h-3 aspect-w-4 overflow-hidden bg-gray-100\"><div data-url=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(helpers.GetStrapiMediaUrl(slide.Attributes.Url)))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" class=\"slide bg-cover bg-no-repeat bg-center h-screen\"></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></div><div class=\"w-full text-center text-white text-xl leading-6 absolute bottom-10 z-10\"><span class=\"text-center inline-block transition-all ease-in-out duration-700\" _=\"on load repeat toggle .-translate-y-10 until transitionend then wait for transitionend end\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\" class=\"w-8 h-8 text-white\"><path fill-rule=\"evenodd\" d=\"M9.47 15.28a.75.75 0 0 0 1.06 0l4.25-4.25a.75.75 0 1 0-1.06-1.06L10 13.69 6.28 9.97a.75.75 0 0 0-1.06 1.06l4.25 4.25ZM5.22 6.03l4.25 4.25a.75.75 0 0 0 1.06 0l4.25-4.25a.75.75 0 0 0-1.06-1.06L10 8.69 6.28 4.97a.75.75 0 0 0-1.06 1.06Z\" clip-rule=\"evenodd\"></path></svg></span><p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(props.CTA)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/pages/index.templ`, Line: 49, Col: 15}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p></div></div><script src=\"https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js\"></script><link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = initSwiper().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func initSwiper() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_initSwiper_72fc`,
		Function: `function __templ_initSwiper_72fc(){document.querySelectorAll('.slide').forEach(elm => {
		elm.setAttribute('style', ` + "`" + `background-image: url('${elm.getAttribute('data-url')}')` + "`" + `);
	})

    const s = new Swiper("#wallpaper-swiper", {
      effect: "fade",
      fadeEffect: {
        crossFade: true,
      },
    });
    s.autoplay.start();
}`,
		Call:       templ.SafeScript(`__templ_initSwiper_72fc`),
		CallInline: templ.SafeScriptInline(`__templ_initSwiper_72fc`),
	}
}
